apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flick

labels:
  - pairs:
      app.kubernetes.io/part-of: flick
    includeSelectors: true

resources:
  - kube-state-metrics.yaml
  - node-exporter.yaml
