apiVersion: v1
kind: Secret
metadata:
  name: flick-secrets
type: Opaque
stringData:
  FLICK_INTERNAL_TOKEN: "replace-me-before-use"
  FLICK_METRICS_TOKEN: "replace-me-before-use"
  FLICK_OCI_AUTH_MODE: "instance_principal"
  FLICK_OCI_REGION: ""
  FLICK_OCI_NAMESPACE: ""
  FLICK_OCI_BUCKET: ""
  FLICK_OCI_COMPARTMENT_OCID: ""
